services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Netresearch\Demio\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Netresearch\Demio\Controller\EventController:
    arguments:
      $demioService: '@Netresearch\Demio\Service\DemioService'
