services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Netresearch\T3Demio\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Netresearch\T3Demio\Controller\ListController:
    arguments:
      $demioService: '@Netresearch\T3Demio\Service\DemioService'
  Netresearch\T3Demio\Controller\SingleController:
    arguments:
      $demioService: '@Netresearch\T3Demio\Service\DemioService'